apiVersion: apps/v1beta2
kind: Depoyment
metadata:
  name: gcp-devops-prod
spec:
  replicas: 1
  selector:
    matchlabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/civil-epoch-402617/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"